server:
    host: ENC[AES256_GCM,data:ATJwnq3Pdg==,iv:nrrYUsYgKMcv7nOkbXEGCNHM/bjNz6SXYnE1WZGD0GE=,tag:b64fT5n0DOzAHks8tImCGQ==,type:str]
    port: ENC[AES256_GCM,data:Z56x+g==,iv:6wD9RxPXS/5ziz2IyMo9UfTLK1fP6X4pBTj5vkrZXWo=,tag:V688AxgHtc6GJmLSCDLe7Q==,type:int]
    #ENC[AES256_GCM,data:VAjMgwPB1vddlTRgIRRFzg==,iv:LUtTOV1r8LBVDhHncOMDIPLFNKqfdycwZe1Gp2SOcII=,tag:TIZSftkDzNufKvy02+00pw==,type:comment]
    mode: ENC[AES256_GCM,data:wE/CdGI=,iv:vE7SMR986v/2l4mD4Sd6InKoTbdDGubLne1kjLBcFdY=,tag:0PG6SKPtmE/OqbJUBVjybw==,type:str]
database:
    host: ENC[AES256_GCM,data:rcCozQXQsUA0Gn0=,iv:+zXg4mWV3uIcEEAK4fSerRvHSCYyWmGnxa2g/pfcb04=,tag:LWA98hP3kLy60n84KQoN0Q==,type:str]
    port: ENC[AES256_GCM,data:rqIdWHY=,iv:rJnxxC4cGllhC4fsoDVx0ZHKC5Npm3inA6yEyF9Y/rE=,tag:S+nfeYAtddBR1YbrGbBXnw==,type:int]
    user: ENC[AES256_GCM,data:80EaV7/Zw2Dt6wc=,iv:k5VQkhdG1o5Uv9W9CnNmHbIe4s1E/bL9M/IfsG+6V9E=,tag:BG9TEH7VuEOnusQ2G3GXYA==,type:str]
    password: ENC[AES256_GCM,data:Rj+WcibaA8r4,iv:txWHEAlZ8pBOdGJHLqQdVDNx9uY9CoBGWfYaRyB4VRQ=,tag:gTOrLFXmnpqH0Y2JPVOCwQ==,type:str]
    name: ENC[AES256_GCM,data:JBEFJtOjj1ZeiZ/Yq3ovcPREXg==,iv:LNtIibUk3n3FvqMpo3p9NqIlnj3B4KpIG7fvbENaxLk=,tag:FKz5Hh7pqO3tHJHsibXabg==,type:str]
    ssl_mode: ENC[AES256_GCM,data:fAm8kaQ8wQ==,iv:fy7jYc3rc1e3RB0uvxdy+wvSH3gORPQxOveeo5L5NCc=,tag:upuyPaqEAdJWIH4eltom7g==,type:str]
    max_conns: ENC[AES256_GCM,data:0vs=,iv:ETJ4aDRqjPzbpVnhZrUc6CNDkHtRQflMkcfJ8cNNk78=,tag:T784/p6DtYJdWQDVprKdyg==,type:int]
    min_conns: ENC[AES256_GCM,data:rQ==,iv:xy1ZY0cFTj+nVIzCwaklKCbCgUQA0iRK/I9WLMeosVs=,tag:CwiLnAT7vqCUNHnQThojYQ==,type:int]
rabbitmq:
    url: ENC[AES256_GCM,data:uMNEpSimfFPHpdHehHhDejBZy+n/+wDlC2mrvdWmaZcyGpGO,iv:KlGPoDXwMFtkKqSqx08aPz4mUubNocfjoFtRVNsg/U4=,tag:L2nJBONndM7dbPP9uXNBKQ==,type:str]
    prefetch_count: ENC[AES256_GCM,data:v7c=,iv:y7psx18x7fdeLkksIeq0tqe4nLEO4yhJd51dN4VMGDg=,tag:KJJueUPX2thRMUqDQvoZ9Q==,type:int]
keycloak:
    base_url: ENC[AES256_GCM,data:ehf85N+RdTwDQHPAhWPGUxmXY5ESMYQ=,iv:xB+XVZQYqsPtWPBWlhzb0fFoM2jWUEcxNsOQkWeLQhQ=,tag:NKzgHvf9MlClVTKPbn0SmA==,type:str]
    realm: ENC[AES256_GCM,data:DVU4lLl4zBY=,iv:tfRS9xgJ3i3sRiomXE2SQtArwR7kxqXOU/K3N1zK4zQ=,tag:8W91VFW9ni7c69BAhbENxQ==,type:str]
    client_id: ENC[AES256_GCM,data:myauDUn68PZ0BlExWc17UmFcEajGprN4,iv:NqnbdAkqCR3wxSEwSS/u6hn99jHOR3SlECphpTpMTOk=,tag:KsoT8xJbHdZtnF/5viC6Rw==,type:str]
    client_secret: ENC[AES256_GCM,data:iDcBcxs2lxTY4XrA6JnguP6TVnB60oWaOduwp/HVLkY=,iv:IxUYf1OXCBNBXtw4wgIDrZ8hEtdZrrlyHPrNOHxq+IM=,tag:huuyiu8tp3vQKR35dVkzPw==,type:str]
worker:
    concurrency: ENC[AES256_GCM,data:cDM=,iv:WsTI09fOWVpU1k5UWgsyiKJmdZD6qZC7URszg9d0nLg=,tag:9x8mHh37xrJK+tx3nae4qA==,type:int]
    max_retry: ENC[AES256_GCM,data:0Q==,iv:L9HST+MVku6nppVwbnjX0ZVlQIMOfoGM/qw4PElQdDg=,tag:1n5IY+wqT/SKRrhBGsVrtQ==,type:int]
    retry_delay: ENC[AES256_GCM,data:op0=,iv:XkJIf8DK7zMyxwNT0Jwby7gQGsdxvZ3oeONqI4nlPXQ=,tag:gQ8Bal1azdCnEzq9f40OVw==,type:str]
logging:
    #ENC[AES256_GCM,data:/pEClGUk8j935+fVzSWpy46/tuYgiNdAafNUgw==,iv:AY2bOLV09DlWpkB+eoQnyHVNpf6wdAgtvq33borrSXY=,tag:nE5VHOiROw53N7dRdSULIw==,type:comment]
    level: ENC[AES256_GCM,data:Y+Vvc2Q=,iv:zPX8aZHH+rA9lXeRBlSw9ibaclM5D08BUx5cMAeQ+Z8=,tag:cJpkzcabdb5/HQ2Ab1zVAg==,type:str]
    #ENC[AES256_GCM,data:LobehuxaGsTfPBL2,iv:p2tlog+U4isXbuP01RvuuPAHF67eSn1e8Aj/zZ7zcoI=,tag:XMMyL7QZOub+sT3CC2NUWw==,type:comment]
    format: ENC[AES256_GCM,data:iHh0fg==,iv:7oYWC/zP3LZGkkxbP+hcu1eBpwqUhHGk/wH9bg8hX+k=,tag:mn/PfIvN9errtdwJEKf4GQ==,type:str]
sops:
    age:
        - recipient: age1465mw0a9jxf2kk5vkmgktnrknlzhgz0uq8qy8x9dzmvq9l9lxa4qz3g796
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldXFnd2FzaHBQalNGcWRx
            b1QyTE5oWmhzVUFDVmYycVpPOTVwNDJSNnhJCklEdWFMc2VtdUU5Tk1EalpNbEFi
            UVQ5R0czL0tqY0JadVR2bVVGeDI3bUkKLS0tIHlKVUJDemNNM3RUcjVhTmkyWCtL
            U3Vra3NSYU5VMk40bFpwSUFSZTYvcU0KEbi1575H6X9iB9LXwwd/T7J2C1zHwdUA
            YalmRCgzKs2ZGvtctzgH/IF27UJ9pDyi9wSIBOfB19lfGDCHztIjbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T17:24:15Z"
    mac: ENC[AES256_GCM,data:mF+fn9D+tqVbIfdN3BGSbcbm5rX0/bTzxkFjuxWKETMYwPr4FOo2JbekZHBOyPfHZFhyXsmw1zP5FwHSe+ZQAbpIlshdzFJOZcfdm5bCOVGtb//AdhKJ5tcIT1eyJbqb/luxCRHUefqhALQ8L0G6S7+pHfiBqdxuE47u65WToUk=,iv:bm5DEVTEWTYv4iKH7lK4BBWXroxwyRnHwqWGqRKfVIA=,tag:dfmSPKM3zxHlWoaBTnlpWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
